### ISSUE TITLE
Portal stuff

### ISSUE THREAD

**Issue by jamesk629** [Manny500/TrelloV2#16]
Portal stuff: 
-login 
-oauth2  security for each login
-progress display
-home display
-company(?)

**Comment by Manny500** [comment]
Unless you have a good handle on security or are almost done with it skip it for now. Focus on refactoring the project first. Then we can work on security.

**Comment by Manny500** [comment]
Tasks:
home display,
navbar display

**Comment by Manny500** [comment]
Done with nav and home
