### ISSUE TITLE
jenkins/ profile page

### ISSUE THREAD

**Issue by Clement1229** [Manny500/TrelloV2#17]
so Steve just mentioned pipeline is not required for this project...
Since I've already done some research, i'll still do some test later to see if it works.
St the same time i'm working on re-building angular hero example(almost done), after that i'll start to work on the profile microservice/ component.

**Comment by Manny500** [comment]
Yes, focus on getting our app refactored first. After that if we have time we can add the pipeline

**Comment by Manny500** [comment]
Tasks: 
view profile,
update profile,
Register user page.
